FROM docker.io/bitnami/spark:3.3

USER root
RUN apt-get update && \
  apt-get install -y \
  wget 

RUN mkdir /home/downloads && \
    cd /home/downloads && \
    wget https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-latest-hadoop2.jar && \
    cp *.jar $SPARK_HOME/jars
ENV GOOGLE_APPLICATION_CREDENTIALS=/home/keys/airflow4i-key.json
